# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tGSvTMjCg0dRO7ZzjTzAeTB57ZPXQsy6
"""

import pandas as pd
baza ={
    "FISH":["Maxmudov Bekmurod","Anvarov Alisher","Zokirova Zarina","Maxkamova Sharifa","Tojiboyev Lazizbek","Tursunova Zilola"],
    "Yoshi":['19','25','37','21','29','30'],
    "Manzili":["Andijon shaxari","Andijon shaxari","Samarqand shaxari",'Andijon shaxari',"Farg'ona shaxari","Toshkent shaxari"],
    "Jinsi":['erkak','erkak','ayol','ayol','erkak','ayol'],
    "Ishlash_joyi":["DXX","TATUFF","FARDU",'ADU','FARDU','TATUFF']

}

db=pd.DataFrame(baza)
db_sorted = db.sort_values(by="FISH").reset_index(drop=True)
print(db_sorted)

filtr=db[(db['Jinsi']=='ayol') & (db['Ishlash_joyi']=="TATUFF") & (db['Yoshi']>='25')]
print(filtr)